In [1]:
import AlgUtils
import numpy as np

In [3]:
txt = """
    175 153 125 104 88 60 39 24 15 11 24 49 59 81 109
    133 116 92 79 62 52 31 18 9 8 24 30 44 67 81
    85 72 63 53 42 34 26 13 4 9 13 29 30 42 54
    46 41 36 34 22 21 12 7 6 10 11 15 25 30 28
    18 13 14 14 10 7 13 10 3 3 3 11 12 10 15
    21 19 10 10 9 9 10 6 4 9 3 7 6 11 13
    52 44 39 29 28 19 14 13 10 4 7 14 18 31 33
    8 72 64 52 40 35 20 13 6 4 12 24 35 46 52
    27 116 96 81 61 48 30 20 6 5 25 39 49 68 74
    76 146 126 101 81 68 42 25 12 15 26 46 63 82 101
    18 189 156 129 100 82 53 33 11 11 37 53 78 109 132
    64 227 196 155 125 94 65 39 12 13 38 65 99 131 163
    18 273 227 191 146 116 74 39 13 17 47 78 108 150 184
    65 309 261 214 171 131 92 50 17 13 51 88 132 169 213
    16 357 298 253 195 145 100 57 21 17 61 98 142 197 249
"""

space = AlgUtils.table_to_np(txt, np.int64)
print(space)

[[175 153 125 104  88  60  39  24  15  11  24  49  59  81 109]
 [133 116  92  79  62  52  31  18   9   8  24  30  44  67  81]
 [ 85  72  63  53  42  34  26  13   4   9  13  29  30  42  54]
 [ 46  41  36  34  22  21  12   7   6  10  11  15  25  30  28]
 [ 18  13  14  14  10   7  13  10   3   3   3  11  12  10  15]
 [ 21  19  10  10   9   9  10   6   4   9   3   7   6  11  13]
 [ 52  44  39  29  28  19  14  13  10   4   7  14  18  31  33]
 [  8  72  64  52  40  35  20  13   6   4  12  24  35  46  52]
 [ 27 116  96  81  61  48  30  20   6   5  25  39  49  68  74]
 [ 76 146 126 101  81  68  42  25  12  15  26  46  63  82 101]
 [ 18 189 156 129 100  82  53  33  11  11  37  53  78 109 132]
 [ 64 227 196 155 125  94  65  39  12  13  38  65  99 131 163]
 [ 18 273 227 191 146 116  74  39  13  17  47  78 108 150 184]
 [ 65 309 261 214 171 131  92  50  17  13  51  88 132 169 213]
 [ 16 357 298 253 195 145 100  57  21  17  61  98 142 197 249]]


In [14]:
def local(space, initial):

    step = 0
    x = initial[0]
    y = initial[1]
    val = space[x,y]
    
    path = [{
        "step": step,
        "location": [x, y],
        "name": "start",
        "value": val,   
    }]

    dirs = [
        ( 0, -1, "left"),
        # (+1, -1, "down-left"),
        (+1,  0, "down"), 
        # (+1, +1, "down-right"), 
        ( 0, +1, "right"),
        # (-1, +1, "up-right"),
        (-1  ,0, "up"),
        # (-1, -1, "up-left"),
    ]

    while True:
        step += 1
        best_found = False
        best_val = val
        best_x = None
        best_y = None
        best_name = None
        for dir in dirs:

            # test if position is inside space boundaries
            xn = x+dir[0]
            yn = y+dir[1]
            if(xn < 0 or xn >= space.shape[0] or yn < 0 or yn >= space.shape[1]):
                continue

            # test if value is better than previous best value
            if(space[xn,yn] < best_val):
                best_x = xn
                best_y = yn
                best_found = True
                best_val = space[xn,yn]
                best_name = dir[2]

        # stop if no better value was found in all directions
        if(not best_found):
            break

        # store current step
        x = best_x
        y = best_y
        val = best_val
        path.append({
            "step": step,
            "location": [x, y],
            "name": best_name,
            "value": val,
        })

    return path

path = local(space, initial=(7+7, 7+7))

for step in path:
    print(step)
    

{'step': 0, 'location': [14, 14], 'name': 'start', 'value': 249}
{'step': 1, 'location': [14, 13], 'name': 'left', 'value': 197}
{'step': 2, 'location': [14, 12], 'name': 'left', 'value': 142}
{'step': 3, 'location': [14, 11], 'name': 'left', 'value': 98}
{'step': 4, 'location': [14, 10], 'name': 'left', 'value': 61}
{'step': 5, 'location': [14, 9], 'name': 'left', 'value': 17}
{'step': 6, 'location': [13, 9], 'name': 'up', 'value': 13}
